version: '3'

services:
  api:
    container_name: mongster-api
    ports:
      - "1337:1337"
    image: ghcr.io/mallgroup/mal-mongster/api:4.4
    environment:
      - NODE_ENV
      - MONGO_CONNECTION
    networks:
      - mongster
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm test
    build:
      context: .
      dockerfile: Dockerfile-api

  mongodb:
    container_name: mongster-mongo
    image: ghcr.io/mallgroup/mal-mongster/mongo:4.4.6-bionic
    ports:
      - "27017:27017"
    networks:
      - mongster

networks:
  mongster:
