version: '3'

services:
  api:
    restart: always
    container_name: api
    ports:
      - "1337:1337"
    image: docker pull ghcr.io/mallgroup/mal-mongster/api:4.4
    environment:
      NODE_ENV: production
      CONFIG_CORS_ALLOW_ORIGINS: '*'
      MONGO_CONNECTION: mongodb:27017/mongster
    links:
      - mongodb
    depends_on:
      - mongodb

  admin:
    container_name: admin
    ports:
      - "8080:80"
    image: docker pull ghcr.io/mallgroup/mal-mongster/admin:4.4
    depends_on:
      - api

  mongodb:
    container_name: mongo
    image: bitnami/mongodb:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami

volumes:
  mongodb_data:
    driver: local
