version: '3'

services:
  api:
    restart: always
    container_name: mongster-api
    ports:
      - "1337:1337"
    image: ghcr.io/mallgroup/mal-mongster/api:4.4
    environment:
      - NODE_ENV
      - MONGO_CONNECTION
    networks:
      - mongster

  admin:
    container_name: mongster-admin
    ports:
      - "8080:80"
    image: ghcr.io/mallgroup/mal-mongster/admin:4.4
    networks:
      - mongster

  mongodb:
    container_name: mongster-mongo
    image: ghcr.io/mallgroup/mal-mongster/mongo:4.4.6-bionic
    ports:
      - "27017:27017"
    networks:
      - mongster
    volumes:
      - ./mongodb_data:/data

networks:
  mongster:
